const area = document.querySelector("#test-area");
const prompt = document.querySelector("#prompt"), sub = document.querySelector("#sub-prompt"), label = document.querySelector("#state-label");
const latest = document.querySelector("#latest"), best = document.querySelector("#best"), attempts = document.querySelector("#attempts"), tip = document.querySelector("#tip"), tabs = document.querySelectorAll(".tab");
let mode = "classic", state = "idle", timer, frame, started = 0, target = 5000, lastTarget = 0, direction = "", memorySequence = [], memoryIndex = 0, count = 0, record = 0;
const copy = { classic: ["READY WHEN YOU ARE", "Tip: wait for the panel to turn green, then hit Space as quickly as you can."], f1: ["STARTING GRID", "Tip: the five red lights will go out at a random moment. Launch on lights out."], timing: ["PRECISION STOP", "Tip: start the timer, then stop it as close to the target as you can."], mind: ["ODD / EVEN", "Tip: wait for a number, then press O for odd or E for even."], memory: ["MEMORY SEQUENCE", "Tip: memorize the light sequence, then repeat it with keys 1–4."] };
const set = (el, value) => el.textContent = value;
const ms = value => `${value} ms`;
function cancel() { clearTimeout(timer); cancelAnimationFrame(frame); }
function stateTo(next) { state = next; area.className = `test-area ${mode} ${next}`; }
function load() { count = Number(localStorage.getItem(`reaction-${mode}-attempts`) || 0); record = Number(localStorage.getItem(`reaction-${mode}-best`) || 0); set(attempts, count); if (mode === "timing") set(best, record ? `${record} ms off` : "—"); else if (mode === "memory") set(best, record ? `Level ${record}` : "—"); else set(best, record ? ms(record) : "—"); } function save(score, display) { count++; localStorage.setItem(`reaction-${mode}-attempts`, count); set(latest, display); const newBest = !record || score < record; if (newBest) { record = score; localStorage.setItem(`reaction-${mode}-best`, score); } load(); return newBest; }
function reset() { cancel(); stateTo("idle"); set(label, copy[mode][0]); set(tip, copy[mode][1]); area.querySelectorAll(".f1-lights i").forEach(light => light.classList.remove("active")); if (mode === "classic") { prompt.innerHTML = "Press <strong>Space</strong> to start"; set(sub, "Keep your eyes on the screen."); } else if (mode === "f1") { prompt.innerHTML = "Press <strong>Space</strong> to line up"; set(sub, "React when every red light goes out."); } else if (mode === "timing") { const choices = [3000, 5000, 8000].filter(value => value !== lastTarget); target = choices[Math.floor(Math.random() * choices.length)]; lastTarget = target; prompt.innerHTML = `Stop at <strong>${(target / 1000).toFixed(1)} seconds</strong>`; set(sub, "Press Space to start the stopwatch."); } else if (mode === "mind") { prompt.innerHTML = "Press <strong>Space</strong> to begin"; set(sub, "Then press O for odd, or E for even."); } else { prompt.innerHTML = "Press <strong>Space</strong> to begin"; set(sub, "Watch the colors, then repeat them with keys 1–4."); } }
function classicStart() { stateTo("waiting"); set(label, "GET READY"); set(prompt, "Wait for green…"); set(sub, "Do not press too soon."); timer = setTimeout(() => { stateTo("go"); set(label, "GO! GO! GO!"); set(prompt, "PRESS SPACE!"); set(sub, "Now."); started = performance.now(); }, 1500 + Math.random() * 3000); }
function f1Start() { clearTimeout(timer); area.querySelectorAll(".f1-lights i").forEach(light => light.classList.remove("active")); stateTo("f1-building"); set(label, "LIGHTS SEQUENCE"); set(prompt, "Hold steady…"); set(sub, "Five lights incoming."); let lightCount = 0; const next = () => { lightCount++; area.querySelectorAll(".f1-lights i")[lightCount - 1].classList.add("active"); if (lightCount < 5) timer = setTimeout(next, 650); else timer = setTimeout(() => { stateTo("f1-go"); set(label, "GREEN LIGHT"); set(prompt, ""); set(sub, "Press Space as soon as the green light appears."); started = performance.now(); }, 900 + Math.random() * 1800); }; timer = setTimeout(next, 500); }
function mindStart() { stateTo("waiting"); set(label, "GET READY"); set(prompt, "Wait for the number…"); set(sub, "Do not press O or E too soon."); timer = setTimeout(() => { const number = 1 + Math.floor(Math.random() * 9); direction = number % 2 ? "KeyO" : "KeyE"; stateTo("mind-go"); set(label, "ODD OR EVEN?"); set(prompt, String(number)); set(sub, "O = odd · E = even"); started = performance.now(); }, 1200 + Math.random() * 2500); } function mindAnswer(key) { if (state === "waiting") { falseStart(); return; } if (state !== "mind-go") return; if (key !== direction) { stateTo("too-soon"); set(label, "NOT QUITE"); set(prompt, "Try again"); set(sub, "Press Space to start a new round."); return; } finishReaction(); } function memoryStart() { memorySequence = [1 + Math.floor(Math.random() * 4)]; memoryIndex = 0; playMemory(); } function playMemory() { stateTo("memory-show"); set(label, "WATCH CLOSELY"); set(prompt, `Level ${memorySequence.length}`); set(sub, "Memorize the colors."); let flashIndex = 0; const flash = () => { if (flashIndex >= memorySequence.length) { stateTo("memory-input"); set(label, "YOUR TURN"); set(prompt, `Level ${memorySequence.length}`); set(sub, "Repeat it using keys 1, 2, 3, 4."); return; } const light = area.querySelector(`[data-memory="${memorySequence[flashIndex]}"]`); light.classList.add("flash"); timer = setTimeout(() => { light.classList.remove("flash"); flashIndex++; timer = setTimeout(flash, 190); }, 520); }; timer = setTimeout(flash, 420); } function memoryAnswer(key) { if (state !== "memory-input") return; const value = Number(key.replace("Digit", "").replace("Numpad", "")); if (value !== memorySequence[memoryIndex]) { stateTo("too-soon"); set(label, "SEQUENCE ENDED"); set(prompt, `Level ${memorySequence.length}`); set(sub, "Press Space to start a new sequence."); return; } memoryIndex++; if (memoryIndex === memorySequence.length) { count++; localStorage.setItem("reaction-memory-attempts", count); set(latest, `Level ${memorySequence.length}`); if (memorySequence.length > record) { record = memorySequence.length; localStorage.setItem("reaction-memory-best", record); } load(); memorySequence.push(1 + Math.floor(Math.random() * 4)); memoryIndex = 0; timer = setTimeout(playMemory, 700); } } function falseStart() { cancel(); stateTo("too-soon"); set(label, "FALSE START"); set(prompt, "Too soon!"); set(sub, mode === "f1" ? "Resetting the starting grid…" : "Press Space to try again."); if (mode === "f1") timer = setTimeout(() => { reset(); f1Start(); }, 1100); }
function finishReaction() { const time = Math.round(performance.now() - started), newBest = save(time, ms(time)); stateTo("complete"); set(label, newBest ? "NEW PERSONAL BEST" : "RESULT RECORDED"); set(prompt, ms(time)); set(sub, "Press Space to go again."); }
function tick() { set(prompt, `${((performance.now() - started) / 1000).toFixed(3)} s`); frame = requestAnimationFrame(tick); }
function startTiming() { started = performance.now(); stateTo("timing-running"); set(label, `TARGET: ${(target / 1000).toFixed(1)} SECONDS`); set(sub, "Press Space to stop."); tick(); }
function finishTiming() { cancelAnimationFrame(frame); const elapsed = Math.round(performance.now() - started), off = Math.abs(elapsed - target), newBest = save(off, `${off} ms off`); stateTo("complete"); set(label, newBest ? "NEW PERSONAL BEST" : "TIME RECORDED"); set(prompt, `${(elapsed / 1000).toFixed(3)} s`); set(sub, `${off} ms from target. Press Space for a new target.`); }
function action() { if (mode === "timing") { if (state === "timing-running") finishTiming(); else if (state === "complete") reset(); else startTiming(); return; } if (mode === "memory") { if (["idle", "complete", "too-soon"].includes(state)) memoryStart(); else if (state === "memory-input") { set(label, "USE KEYS 1–4"); set(sub, "Repeat the color sequence with your keyboard."); } return; } if (["idle", "complete", "too-soon"].includes(state)) { if (mode === "classic") classicStart(); else if (mode === "f1") f1Start(); else mindStart(); } else if (["waiting", "f1-building"].includes(state)) falseStart(); else if (mode === "mind") { set(label, "USE O OR E"); set(sub, "Press O for odd, or E for even."); } else finishReaction(); }
tabs.forEach(tab => tab.addEventListener("click", () => { mode = tab.dataset.mode; tabs.forEach(item => { const active = item === tab; item.classList.toggle("active", active); item.setAttribute("aria-selected", active); }); reset(); load(); }));
document.addEventListener("keydown", event => { if (event.code === "Space" && !event.repeat) { event.preventDefault(); action(); } else if (mode === "mind" && !event.repeat && ["KeyO", "KeyE"].includes(event.code)) { event.preventDefault(); mindAnswer(event.code); } else if (mode === "memory" && !event.repeat && ["Digit1", "Digit2", "Digit3", "Digit4", "Numpad1", "Numpad2", "Numpad3", "Numpad4"].includes(event.code)) { event.preventDefault(); memoryAnswer(event.code); } });
area.addEventListener("click", action); reset(); load();
